# Generated by Django 4.2 on 2026-05-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="preview",
            field=models.ImageField(
                blank=True,
                default="blog_previews/preview.jpeg",
                null=True,
                upload_to="blog_previews/",
                verbose_name="Превью (изображение)",
            ),
        ),
    ]
