# Generated by Django 4.2 on 2026-05-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(default="Описание отсутствует", verbose_name="Описание категории"),
        ),
        migrations.AlterField(
            model_name="product",
            name="details",
            field=models.TextField(default="Описание отсутствует", verbose_name="Описание продукта"),
        ),
        migrations.AlterField(
            model_name="product",
            name="img",
            field=models.ImageField(
                blank=True,
                help_text="Загрузи фото товара",
                null=True,
                upload_to="products/",
                verbose_name="Изображение",
            ),
        ),
    ]
